id: opecha:P000750
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4454
  title: དཔལ་ལྡན་ཆོས་རྗེའི་བདེན་གཉིས་དང་ཞྭ་དམར་དྲང་ངེས་ཟིན་བྲིས་ལེགས་བཤད་སྙིང་པོའི་མཆན་དབྱོར
  volume: ''
  author: ''
