id: I0E58EE22
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:32:53+00:00'
last_modified: '2022-06-07T13:37:53.186694+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4454
  title: དཔལ་ལྡན་ཆོས་རྗེའི་བདེན་གཉིས་དང་ཞྭ་དམར་དྲང་ངེས་ཟིན་བྲིས་ལེགས་བཤད་སྙིང་པོའི་མཆན་དབྱོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0523':
      image_group_id: I1KG4569
      title: ''
      total_pages: 294
      order: 1
      base_file: 0523.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
